server:
  port: 8888
  servlet:
    context-path: /springboot
spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.131.87.154:3306/sys?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: '123456'
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java  #重启目录
  redis:
    database: 0
    host: localhost
    port: 6379
    password: ''
    lettuce:
      pool:
        max-wait: -1  #连接池最大阻塞等待时间(使用负值表示没有限制)
        max-active: 100  #连接池最大连接数
        max-idle: 20  #连接池中的最大空闲连接
        min-idle: 0  #连接池中的最小空闲连接
    timeout: 3000  #连接超时
  data:
    solr:
      host: http://8.131.87.154:8983/solr/firstcore  #firstcore 是自己创建的core
    #mybatis配置
mybatis:
      #mapper配置文件
    mapper-locations: classpath*:mapper/*.xml,classpath*:mapper/mh/*.xml
    type-aliases-package: com.example.springbootpro.entity,com.example.springbootpro.mh.entity

#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
#打印sql
logging:
  level:
    com.example.springbootpro.mapper : debug
#图片路径本地
#imgPath: d:/image/
#图片路径服务器
imgPath: /usr/local/image/

